### PR TITLE
Front additions and new problem endpoints for future

### PR DESCRIPTION
**Pull request by sskhi1**

### CODE REVIEW

**Comment by sskhi1** [comment]
I hope you're doing great! I've made some changes to the [feature/branch name] and would really appreciate your review. Your expertise has always been invaluable, and I'd love to get your insights on this. Thanks a lot for your help, as always!

**Comment by aadua20** [comment]
impressive

**Comment by aadua20** [comment]
Excellent job on implementing this feature! I appreciate the thoroughness of your approach, especially the way you optimized the algorithm to improve performance. The code is clean and well-documented, which makes it easy to understand and maintain. Keep up the great work!

**Comment by sskhi1** [comment]
@aadua20 Thank you so much for the kind words! I’m really glad you found the implementation effective. Your feedback means a lot, and it’s great to know that the code meets your expectations. I’ll continue striving to deliver quality work. Thanks again for your support!

**Comment by zkenshinx** [comment]
My cat has thoroughly reviewed this pull request and enthusiastically exclaimed, "Meow meow meow, meow meow meow meow, MEOW MEow??!?? meow meow!" 🐱✨

**Review by zkenshinx — APPROVED** [review]

**Comment by sskhi1** [comment]
@zkenshinx I’m honored to receive such high praise from your cat! Please let them know that their meows of approval have made my day. I’ll do my best to keep the code feline-friendly! 😸✨

**Pull request merged**
